### ISSUE TITLE
caper submit without call-caching?

### ISSUE THREAD

**Issue by biodavidjm** [ENCODE-DCC/caper#104]
Is it possible to do `caper submit` but to choose not to do the call-catching? I.e, even if I submit the exact same job, to use a parameter to force Cromwell to do everything from the beginning again (but with a new id, obviously). Thanks!!

**Comment by leepc12** [comment]
You can control call-caching behavior (see the following two parameters) per workflow with a workflow options JSON file.
Make a temporary JSON file and submit it with `caper submit -o`.
```json
{
    "write_to_cache": false,
    "read_from_cache": false
}
```
https://cromwell.readthedocs.io/en/stable/wf_options/Overview/#workflow-options-overview

**Comment by biodavidjm** [comment]
it works! thanks a lot!
