### ISSUE TITLE
Running caper within a docker container

### ISSUE THREAD

**Issue by HenryCWong** [ENCODE-DCC/caper#125]
Is it possible to run caper inside of a docker container while using the --docker flag? I know a docker within a docker container isn't a good idea, but I was hoping to spin up a sibling instance. 
This is because my university's compute cluster requires everyone to run everything within a docker container.

**Comment by leepc12** [comment]
I didn't test such nested container cases. If you are going to run ENCODE pipelines, then pipeline's docker container has all dependencies in it so please use that container first and then install `caper`, pipeline WDL inside it `pip3 install caper`. Then run pipelines locally there (caper's default backend `local`). Make sure that you have enough resource (cpu and mem) inside the container and just run `caper run your.wdl -i your.input.json`

**Comment by HenryCWong** [comment]
Thanks! Right now I'm trying to throw all the dependencies into a docker container and just running it locally. Running into a few errors. I'll move over to that pipeline specific stuff and close this one out.
