### ISSUE TITLE
How does docker get called in caper? 

### ISSUE THREAD

**Issue by HenryCWong** [ENCODE-DCC/caper#126]
Whenever one runs caper with the --docker flag how does the docker container get run? 

I'm only asking because I'm trying to run a wdl file that's supposed to run on caper on miniwdl because caper doesn't run within a docker container. When I run the ENCODE/hic-pipeline I get a "python3 not found" error since the pipeline uses raw commands to call python scripts. It doesn't seem like the miniwdl is calling docker the same way caper is.

**Comment by HenryCWong** [comment]
I just added a docker tag to the runtime in every wdl task. It worked so I'm just going to follow through with that instead.

**Comment by leepc12** [comment]
You can use `--docker` as a flag or define a docker image with that. If it's a flag then Caper tries to find `caper_docker` in WDL's meta.

Caper adds found/specified docker image to `docker` in default runtime attributes for all task. It's a default so `docker` defined in task's `runtime` will override the default one.
