### ISSUE TITLE
No such file or directory: 'singularity'

### ISSUE THREAD

**Issue by HenryCWong** [ENCODE-DCC/caper#128]
I'm trying to run caper on the encode hic-pipeline using singularity using the following command 
`caper run hic.wdl -i tests/functional/json/test_hic.json --singularity`
and I get the following error message: 
```
FATAL:   while extracting ~/.caper/singularity_cachedir/cache/oci-tmp/ad135405272624a90ae386db4d4deaeaff7126532bbd444b071827ea30107530: root filesystem extraction failed: extract command failed: FATAL:   could not open image /~/.caper/singularity_cachedir/rootfs-971186452/tmp-rootfs-720708493: failed to retrieve path for /~/.caper/singularity_cachedir/rootfs-971186452/tmp-rootfs-720708493: lstat /~: no such file or directory
: exit status 255
Traceback (most recent call last):
  File "/home/kos/.local/bin/caper", line 13, in <module>
    main()
  File "/home/kos/.local/lib/python3.8/site-packages/caper/cli.py", line 675, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/home/kos/.local/lib/python3.8/site-packages/caper/cli.py", line 226, in runner
    subcmd_run(c, args)
  File "/home/kos/.local/lib/python3.8/site-packages/caper/cli.py", line 347, in subcmd_run
    thread = caper_runner.run(
  File "/home/kos/.local/lib/python3.8/site-packages/caper/caper_runner.py", line 410, in run
    options = self._caper_workflow_opts.create_file(
  File "/home/kos/.local/lib/python3.8/site-packages/caper/caper_workflow_opts.py", line 234, in create_file
    s.build_local_image()
  File "/home/kos/.local/lib/python3.8/site-packages/caper/singularity.py", line 56, in build_local_image
    return check_call(cmd, env=env)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['singularity', 'exec', 'docker://encodedcc/hic-pipeline:0.4.0', 'echo', 'Built local singularity image for docker://encodedcc/hic-pipeline:0.4.0']' returned non-zero exit status 255.

```

**Comment by leepc12** [comment]
Please run this to check if Singularity works on your system. Here is my result.
```
$ singularity exec docker://encodedcc/hic-pipeline:0.4.0 echo hello world
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob fe703b657a32 done
Copying blob f9df1fafd224 done
Copying blob a645a4b887f9 done
Copying blob 57db7fe0b522 done
Copying blob 58c26648afd2 done
Copying blob f20ee6a53f3a done
Copying blob 4f8a7ebd7d04 done
Copying blob 1f4e21f82bd3 done
Copying blob d7d5e3cabab2 done
Copying blob aee04a596d5c done
Copying blob 641caf1fe70e done
Copying blob 3707b00bd2e7 done
Copying blob a1cc3c83319a done
Copying blob ad92e8d82804 done
Copying config d6051e0df8 done
Writing manifest to image destination
Storing signatures
2021/06/03 14:35:13  info unpack layer: sha256:fe703b657a32e0046dce0ad2cb17172cbec8ba302edf370f5f28962bdb6216a9
2021/06/03 14:35:13  warn rootless{dev/agpgart} creating empty file in place of device 10:175
2021/06/03 14:35:13  warn rootless{dev/audio} creating empty file in place of device 14:4
2021/06/03 14:35:13  warn rootless{dev/audio1} creating empty file in place of device 14:20
2021/06/03 14:35:13  warn rootless{dev/audio2} creating empty file in place of device 14:36
2021/06/03 14:35:13  warn rootless{dev/audio3} creating empty file in place of device 14:52
2021/06/03 14:35:13  warn rootless{dev/audioctl} creating empty file in place of device 14:7
2021/06/03 14:35:13  warn rootless{dev/console} creating empty file in place of device 5:1
2021/06/03 14:35:13  warn rootless{dev/dsp} creating empty file in place of device 14:3
2021/06/03 14:35:13  warn rootless{dev/dsp1} creating empty file in place of device 14:19
2021/06/03 14:35:13  warn rootless{dev/dsp2} creating empty file in place of device 14:35
2021/06/03 14:35:13  warn rootless{dev/dsp3} creating empty file in place of device 14:51
2021/06/03 14:35:13  warn rootless{dev/full} creating empty file in place of device 1:7
2021/06/03 14:35:13  warn rootless{dev/kmem} creating empty file in place of device 1:2
2021/06/03 14:35:13  warn rootless{dev/loop0} creating empty file in place of device 7:0
2021/06/03 14:35:13  warn rootless{dev/loop1} creating empty file in place of device 7:1
2021/06/03 14:35:13  warn rootless{dev/loop2} creating empty file in place of device 7:2
2021/06/03 14:35:13  warn rootless{dev/loop3} creating empty file in place of device 7:3
2021/06/03 14:35:13  warn rootless{dev/loop4} creating empty file in place of device 7:4
2021/06/03 14:35:13  warn rootless{dev/loop5} creating empty file in place of device 7:5
2021/06/03 14:35:13  warn rootless{dev/loop6} creating empty file in place of device 7:6
2021/06/03 14:35:13  warn rootless{dev/loop7} creating empty file in place of device 7:7
2021/06/03 14:35:13  warn rootless{dev/mem} creating empty file in place of device 1:1
2021/06/03 14:35:13  warn rootless{dev/midi0} creating empty file in place of device 35:0
2021/06/03 14:35:13  warn rootless{dev/midi00} creating empty file in place of device 14:2
2021/06/03 14:35:13  warn rootless{dev/midi01} creating empty file in place of device 14:18
2021/06/03 14:35:13  warn rootless{dev/midi02} creating empty file in place of device 14:34
2021/06/03 14:35:13  warn rootless{dev/midi03} creating empty file in place of device 14:50
2021/06/03 14:35:13  warn rootless{dev/midi1} creating empty file in place of device 35:1
2021/06/03 14:35:13  warn rootless{dev/midi2} creating empty file in place of device 35:2
2021/06/03 14:35:13  warn rootless{dev/midi3} creating empty file in place of device 35:3
2021/06/03 14:35:13  warn rootless{dev/mixer} creating empty file in place of device 14:0
2021/06/03 14:35:13  warn rootless{dev/mixer1} creating empty file in place of device 14:16
2021/06/03 14:35:13  warn rootless{dev/mixer2} creating empty file in place of device 14:32
2021/06/03 14:35:13  warn rootless{dev/mixer3} creating empty file in place of device 14:48
2021/06/03 14:35:13  warn rootless{dev/mpu401data} creating empty file in place of device 31:0
2021/06/03 14:35:13  warn rootless{dev/mpu401stat} creating empty file in place of device 31:1
2021/06/03 14:35:13  warn rootless{dev/null} creating empty file in place of device 1:3
2021/06/03 14:35:13  warn rootless{dev/port} creating empty file in place of device 1:4
2021/06/03 14:35:13  warn rootless{dev/ram0} creating empty file in place of device 1:0
2021/06/03 14:35:13  warn rootless{dev/ram1} creating empty file in place of device 1:1
2021/06/03 14:35:13  warn rootless{dev/ram10} creating empty file in place of device 1:10
2021/06/03 14:35:13  warn rootless{dev/ram11} creating empty file in place of device 1:11
2021/06/03 14:35:13  warn rootless{dev/ram12} creating empty file in place of device 1:12
2021/06/03 14:35:13  warn rootless{dev/ram13} creating empty file in place of device 1:13
2021/06/03 14:35:13  warn rootless{dev/ram14} creating empty file in place of device 1:14
2021/06/03 14:35:13  warn rootless{dev/ram15} creating empty file in place of device 1:15
2021/06/03 14:35:13  warn rootless{dev/ram16} creating empty file in place of device 1:16
2021/06/03 14:35:13  warn rootless{dev/ram2} creating empty file in place of device 1:2
2021/06/03 14:35:13  warn rootless{dev/ram3} creating empty file in place of device 1:3
2021/06/03 14:35:13  warn rootless{dev/ram4} creating empty file in place of device 1:4
2021/06/03 14:35:13  warn rootless{dev/ram5} creating empty file in place of device 1:5
2021/06/03 14:35:13  warn rootless{dev/ram6} creating empty file in place of device 1:6
2021/06/03 14:35:13  warn rootless{dev/ram7} creating empty file in place of device 1:7
2021/06/03 14:35:13  warn rootless{dev/ram8} creating empty file in place of device 1:8
2021/06/03 14:35:13  warn rootless{dev/ram9} creating empty file in place of device 1:9
2021/06/03 14:35:13  warn rootless{dev/random} creating empty file in place of device 1:8
2021/06/03 14:35:13  warn rootless{dev/rmidi0} creating empty file in place of device 35:64
2021/06/03 14:35:13  warn rootless{dev/rmidi1} creating empty file in place of device 35:65
2021/06/03 14:35:13  warn rootless{dev/rmidi2} creating empty file in place of device 35:66
2021/06/03 14:35:13  warn rootless{dev/rmidi3} creating empty file in place of device 35:67
2021/06/03 14:35:13  warn rootless{dev/sequencer} creating empty file in place of device 14:1
2021/06/03 14:35:13  warn rootless{dev/smpte0} creating empty file in place of device 35:128
2021/06/03 14:35:13  warn rootless{dev/smpte1} creating empty file in place of device 35:129
2021/06/03 14:35:13  warn rootless{dev/smpte2} creating empty file in place of device 35:130
2021/06/03 14:35:13  warn rootless{dev/smpte3} creating empty file in place of device 35:131
2021/06/03 14:35:13  warn rootless{dev/sndstat} creating empty file in place of device 14:6
2021/06/03 14:35:13  warn rootless{dev/tty} creating empty file in place of device 5:0
2021/06/03 14:35:13  warn rootless{dev/tty0} creating empty file in place of device 4:0
2021/06/03 14:35:13  warn rootless{dev/tty1} creating empty file in place of device 4:1
2021/06/03 14:35:13  warn rootless{dev/tty2} creating empty file in place of device 4:2
2021/06/03 14:35:13  warn rootless{dev/tty3} creating empty file in place of device 4:3
2021/06/03 14:35:13  warn rootless{dev/tty4} creating empty file in place of device 4:4
2021/06/03 14:35:13  warn rootless{dev/tty5} creating empty file in place of device 4:5
2021/06/03 14:35:13  warn rootless{dev/tty6} creating empty file in place of device 4:6
2021/06/03 14:35:13  warn rootless{dev/tty7} creating empty file in place of device 4:7
2021/06/03 14:35:13  warn rootless{dev/tty8} creating empty file in place of device 4:8
2021/06/03 14:35:13  warn rootless{dev/tty9} creating empty file in place of device 4:9
2021/06/03 14:35:13  warn rootless{dev/urandom} creating empty file in place of device 1:9
2021/06/03 14:35:13  warn rootless{dev/zero} creating empty file in place of device 1:5
2021/06/03 14:35:15  info unpack layer: sha256:f9df1fafd224fae3ba34a68dfc401f75bf6bc0c016fe36c61661ca5c7ad729ee
2021/06/03 14:35:15  info unpack layer: sha256:a645a4b887f9613f80fae43432e46423f196a9952d11bb620bef2add7c4ed4ee
2021/06/03 14:35:15  info unpack layer: sha256:57db7fe0b522b7a6069e769606e5ed0913a64e1e0d0030382a922ccf9449211e
2021/06/03 14:35:15  info unpack layer: sha256:58c26648afd25ffd4a50a5b2d0f3541ef59ec48161f6668de9787fdfeb264e9e
2021/06/03 14:35:29  info unpack layer: sha256:f20ee6a53f3a159a6d6b6760a618caf3880f6e351538e3048caa10f2ba51bdc2
2021/06/03 14:35:29  info unpack layer: sha256:4f8a7ebd7d0428a0ce1a8e18939178a46c0a9b2cdb8ebb463d8f8a572b5a3646
2021/06/03 14:35:29  info unpack layer: sha256:1f4e21f82bd35a89bebc3a1271eb998f0e3f581613e5522a0229fc0d409fa2e5
2021/06/03 14:35:29  info unpack layer: sha256:d7d5e3cabab2c6ee0d17181ca4f4eb5d7de9dc2c0707a6dd9cae4baf2abf97e9
2021/06/03 14:35:29  info unpack layer: sha256:aee04a596d5c777ba9efcbe2489ad5b6dac8fde04eddf771e43e08f89646f7c1
2021/06/03 14:35:29  info unpack layer: sha256:641caf1fe70e8daef823759712e61801b7c74d6214c2a1aeb2ca38177037e500
2021/06/03 14:35:30  info unpack layer: sha256:3707b00bd2e7938b5a8cde9782194f7014b8c85bff0c5e0e590917c0b92c49b3
2021/06/03 14:35:31  info unpack layer: sha256:a1cc3c83319a014f92ac373fb873d466221350bdefafaeb99d82b1b86f01a575
2021/06/03 14:35:31  info unpack layer: sha256:ad92e8d82804a9463bcb3d152df74deee143c388c4d23b8c1c614a85be652660
INFO:    Creating SIF file...
hello world
```

Also run this for debugging.
```
$ env | grep SINGULARITY
```

**Comment by HenryCWong** [comment]
I don't get any errors from `singularity exec docker://encodedcc/hic-pipeline:0.4.0 echo hello world` and I don't get any output when I run `env | grep SINGULARITY`

**Comment by leepc12** [comment]
This looks like a Singularity-related error.
Please check if the above command works on a compute node.

**Comment by HenryCWong** [comment]
The compute node I have for my university doesn't give me permissions to use singularity so I can't test it there.

**Comment by HenryCWong** [comment]
@leepc12 does caper send a qsub request for PBS for every task in the passed in .hic file?

**Comment by HenryCWong** [comment]
I think I just found the answer to my own question. But another question, does caper only use the docker container for each time a call is made to a task? or does it use the docker container specified in the meta data across the entire program?

**Comment by leepc12** [comment]
Caper actually wraps `echo "singularity exec IMAGE COMMAND" | qsub ...` for each task.

**Comment by HenryCWong** [comment]
I think I can modify enough stuff in caper to get this working. I am running into other issues so I will close out this issue and start another one.

**Comment by leepc12** [comment]
I think it's better to use `--backend-file` instead of directly modifying `cromwell_backend.py`.
Conf file defined with `--backend-file` overrides caper's built-in cromwell backend conf.

Here is an example `example.custom.backend.conf`.
```
backend {
  providers {
    pbs {
      config {
        submit = """if [ -z \"$SINGULARITY_BINDPATH\" ]; then export SINGULARITY_BINDPATH=${singularity_bindpath}; fi; \
if [ -z \"$SINGULARITY_CACHEDIR\" ]; then export SINGULARITY_CACHEDIR=${singularity_cachedir}; fi;

echo "${if !defined(singularity) then '/bin/bash ' + script
        else
          'singularity exec --cleanenv ' +
          '--home ' + cwd + ' ' +
          (if defined(gpu) then '--nv ' else '') +
          singularity + ' /bin/bash ' + script}" | \
qsub \
    -N ${job_name} \
    -o ${out} \
    -e ${err} \
    ${true="-lnodes=1:ppn=" false="" defined(cpu)}${cpu}${true=":mem=" false="" defined(memory_mb)}${memory_mb}${true="mb" false="" defined(memory_mb)} \
    ${'-lwalltime=' + time + ':0:0'} \
    ${'-lngpus=' + gpu} \
    ${'-q ' + pbs_queue} \
    ${pbs_extra_param} \
    -V
"""
        kill = "qdel ${job_id}"
        check-alive = "qstat ${job_id}"
        job-id-regex = "(\\d+)"
      }
    }
  }
}
```
Modify the `submit` part of this conf. For example, remove `${'-lngpus=' + gpu} \` if your cluster does not support GPU.

Then run it with `caper run ... --backend-file example.custom.backend.conf`

**Comment by HenryCWong** [comment]
I ran with 
```
backend {
  providers {
    pbs {
      config {
        submit = "bsub -J ${job_name} -o ${out} -e ${err} -G compute-oncology -q oncology-interactive -a docker(encodedcc/hic-pipeline:0.4.0)" ${script}""
"""
        kill = "bkill ${job_id}"
        check-alive = "bjobs ${job_id}"
        job-id-regex = "(\\d+)"
      }
    }
  }
}```


```
wongh@compute1-exec-278:/storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline$ caper run hic.wdl -i /storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline/tests/functional/json/test_hic.json --backend-file lsf.backend.conf
2021-06-04 18:25:44,552|caper.caper_base|INFO| Creating a timestamped temporary directory. /storage1/fs1/dspencer/Active/wongh/hic/20210604_182544_543254
2021-06-04 18:25:44,552|caper.caper_runner|INFO| Localizing files on work_dir. /storage1/fs1/dspencer/Active/wongh/hic/20210604_182544_543254
pyparsing.ParseException: Expected "}", found '"'  (at char 256), (line:4, col:149)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/caper", line 13, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 675, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 226, in runner
    subcmd_run(c, args)
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 370, in subcmd_run
    dry_run=args.dry_run,
  File "/usr/local/lib/python3.7/dist-packages/caper/caper_runner.py", line 407, in run
    directory=work_dir, backend=backend, custom_backend_conf=custom_backend_conf
  File "/usr/local/lib/python3.7/dist-packages/caper/caper_backend_conf.py", line 362, in create_file
    hocon_s.merge(s, update=True)
  File "/usr/local/lib/python3.7/dist-packages/caper/hocon_string.py", line 165, in merge
    d = HOCONString(b).to_dict()
  File "/usr/local/lib/python3.7/dist-packages/caper/hocon_string.py", line 146, in to_dict
    c = ConfigFactory.parse_string(hocon_str)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_parser.py", line 181, in parse_string
    return ConfigParser().parse(content, basedir, resolve, unresolved_value)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_parser.py", line 494, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 4065, in parseImpl
    raise ParseSyntaxException._from_exception(pe)
pyparsing.ParseSyntaxException: Expected "}", found '"'  (at char 256), (line:4, col:149)
wongh@compute1-exec-278:/storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline$ vim lsf.backend.conf 
E575: viminfo: Illegal starting char in line: ncer/Active/wongh/out.sam
E575: viminfo: Illegal starting char in line: ^I*^I1622126256^I0
E575: viminfo: Illegal starting char in line: ^I"^I1^I0
Press ENTER or type command to continue
wongh@compute1-exec-278:/storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline$ ;s
bash: syntax error near unexpected token `;'
wongh@compute1-exec-278:/storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline$ ls
 LICENSE     cromwell-workflow-logs   docker	  hic		 lsf.backend.conf		       scripts	'~'
 README.md   cromwell.out	      docs	  hic.wdl	 make_restriction_site_locations.wdl   tests
 caper	     croo_out_def.json	      hello.wdl   hic_pipeline	 requirements-scripts.txt	       tox.ini
wongh@compute1-exec-278:/storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline$ vim lsf.backend.conf 
E575: viminfo: Illegal starting char in line: ncer/Active/wongh/out.sam
E575: viminfo: Illegal starting char in line: ^I*^I1622126256^I0
E575: viminfo: Illegal starting char in line: ^I"^I1^I0
Press ENTER or type command to continue
wongh@compute1-exec-278:/storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline$ caper run hic.wdl -i /storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline/tests/functional/json/test_hic.json --backend-file lsf.backend.conf
2021-06-04 18:35:00,053|caper.caper_base|INFO| Creating a timestamped temporary directory. /storage1/fs1/dspencer/Active/wongh/hic/20210604_183500_023138
2021-06-04 18:35:00,053|caper.caper_runner|INFO| Localizing files on work_dir. /storage1/fs1/dspencer/Active/wongh/hic/20210604_183500_023138
pyparsing.ParseException: Expected {: ... | {{{"=" | ":" | "+="} - [Suppress:({{{"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})} | Suppress:(W:(
))})]... -} ConcatenatedValueParser:([{{{{Suppress:({[Suppress:(W:(
,))] {"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})}) | {Suppress:("include") {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")} | {"required" - Suppress:("(") - {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")}} - Suppress:(")")}}} | Re:('[ \\t]*\\$\\{[^\\}]+\\}[ \\t]*') | : ...} | Forward: {{{{Suppress:("[") -} ListParser:({{ConcatenatedValueParser:([{{{{Suppress:({[Suppress:(W:(
,))] {"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})}) | {Suppress:("include") {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")} | {"required" - Suppress:("(") - {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")}} - Suppress:(")")}}} | Re:('[ \\t]*\\$\\{[^\\}]+\\}[ \\t]*') | : ...} | : ...} | {{{{{Re:('(?P<value>\\d+)\\s*(?P<unit>microseconds|milliseconds|nanoseconds|microsecond|millisecond|nanosecond|seconds|minutes|micros|millis|second|minute|months|nanos|micro|milli|hours|weeks|month|years|nano|hour|week|days|year|day|ns|us|ms|mo|s|m|h|w|d|y)$') | Re:('[+-]?(\\d*\\.\\d+|\\d+(\\.\\d+)?)([eE][+\\-]?\\d+)?(?=$|[ \\t]*([\\$\\}\\],#\\n\\r]|//))')} | "true"} | "false"} | "null"} | {{Re:('""".*?"*""} | {{{{{Re:('(?P<value>\\d+)\\s*(?P<unit>microseconds|milliseconds|nanoseconds|microsecond|millisecond|nanosecond|seconds|minutes|micros|millis|second|minute|months|nanos|micro|milli|hours|weeks|month|years|nano|hour|week|days|year|day|ns|us|ms|mo|s|m|h|w|d|y)$') | Re:('[+-]?(\\d*\\.\\d+|\\d+(\\.\\d+)?)([eE][+\\-]?\\d+)?(?=$|[ \\t]*([\\$\\}\\],#\\n\\r]|//))')} | "true"} | "false"} | "null"} | {{Re:('""".*?"*"""') | Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*')} | Re:('(?:[^^`+?!@*&"\\[\\{\\s\\]\\}#,=\\$\\\\]|\\\\.)+[ \\t]*')}}} | Suppress:({{"\" -} Suppress:(W:(
))})}]...)}}, found '"'  (at char 206), (line:6, col:3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/caper", line 13, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 675, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 226, in runner
    subcmd_run(c, args)
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 370, in subcmd_run
    dry_run=args.dry_run,
  File "/usr/local/lib/python3.7/dist-packages/caper/caper_runner.py", line 407, in run
    directory=work_dir, backend=backend, custom_backend_conf=custom_backend_conf
  File "/usr/local/lib/python3.7/dist-packages/caper/caper_backend_conf.py", line 362, in create_file
    hocon_s.merge(s, update=True)
  File "/usr/local/lib/python3.7/dist-packages/caper/hocon_string.py", line 165, in merge
    d = HOCONString(b).to_dict()
  File "/usr/local/lib/python3.7/dist-packages/caper/hocon_string.py", line 146, in to_dict
    c = ConfigFactory.parse_string(hocon_str)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_parser.py", line 181, in parse_string
    return ConfigParser().parse(content, basedir, resolve, unresolved_value)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_parser.py", line 494, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 4065, in parseImpl
    raise ParseSyntaxException._from_exception(pe)
pyparsing.ParseSyntaxException: Expected {: ... | {{{"=" | ":" | "+="} - [Suppress:({{{"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})} | Suppress:(W:(
))})]... -} ConcatenatedValueParser:([{{{{Suppress:({[Suppress:(W:(
,))] {"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})}) | {Suppress:("include") {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")} | {"required" - Suppress:("(") - {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")}} - Suppress:(")")}}} | Re:('[ \\t]*\\$\\{[^\\}]+\\}[ \\t]*') | : ...} | Forward: {{{{Suppress:("[") -} ListParser:({{ConcatenatedValueParser:([{{{{Suppress:({[Suppress:(W:(
,))] {"#" | "//"} - SkipTo:({Suppress:(W:(
)) | StringEnd})}) | {Suppress:("include") {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")} | {"required" - Suppress:("(") - {Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') | {{"url" | "file" | "package"} - Suppress:("(") - Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*') - Suppress:(")")}} - Suppress:(")")}}} | Re:('[ \\t]*\\$\\{[^\\}]+\\}[ \\t]*') | : ...} | : ...} | {{{{{Re:('(?P<value>\\d+)\\s*(?P<unit>microseconds|milliseconds|nanoseconds|microsecond|millisecond|nanosecond|seconds|minutes|micros|millis|second|minute|months|nanos|micro|milli|hours|weeks|month|years|nano|hour|week|days|year|day|ns|us|ms|mo|s|m|h|w|d|y)$') | Re:('[+-]?(\\d*\\.\\d+|\\d+(\\.\\d+)?)([eE][+\\-]?\\d+)?(?=$|[ \\t]*([\\$\\}\\],#\\n\\r]|//))')} | "true"} | "false"} | "null"} | {{Re:('""".*?"*""} | {{{{{Re:('(?P<value>\\d+)\\s*(?P<unit>microseconds|milliseconds|nanoseconds|microsecond|millisecond|nanosecond|seconds|minutes|micros|millis|second|minute|months|nanos|micro|milli|hours|weeks|month|years|nano|hour|week|days|year|day|ns|us|ms|mo|s|m|h|w|d|y)$') | Re:('[+-]?(\\d*\\.\\d+|\\d+(\\.\\d+)?)([eE][+\\-]?\\d+)?(?=$|[ \\t]*([\\$\\}\\],#\\n\\r]|//))')} | "true"} | "false"} | "null"} | {{Re:('""".*?"*"""') | Re:('"(?:[^"\\\\\\n]|\\\\.)*"[ \\t]*')} | Re:('(?:[^^`+?!@*&"\\[\\{\\s\\]\\}#,=\\$\\\\]|\\\\.)+[ \\t]*')}}} | Suppress:({{"\" -} Suppress:(W:(
))})}]...)}}, found '"'  (at char 206), (line:6, col:3)
```

If you think I should just make a new issue let me know. 
And I'm getting a

**Comment by HenryCWong** [comment]
When I run 
```
LSF {
  actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
  config {
    submit = "bsub -J ${job_name} -o ${out} -e ${err} -G compute-oncology -q oncology-interactive -a docker(encodedcc/hic-pipeline:0.4.0)" ${script}"
    kill = "bkill ${job_id}"
    check-alive = "bjobs ${job_id}"
    job-id-regex = "Job <(\\d+)>.*"
  }
}
```

```
wongh@compute1-exec-278:/storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline$ caper run hic.wdl -i /storage1/fs1/dspencer/Active/wongh/hic2/hic-pipeline/tests/functional/json/test_hic.json --backend-file lsf2.backend.conf
2021-06-04 18:39:16,449|caper.caper_base|INFO| Creating a timestamped temporary directory. /storage1/fs1/dspencer/Active/wongh/hic/20210604_183916_440922
2021-06-04 18:39:16,450|caper.caper_runner|INFO| Localizing files on work_dir. /storage1/fs1/dspencer/Active/wongh/hic/20210604_183916_440922
pyparsing.ParseException: Expected "}", found '"'  (at char 253), (line:4, col:149)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/caper", line 13, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 675, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 226, in runner
    subcmd_run(c, args)
  File "/usr/local/lib/python3.7/dist-packages/caper/cli.py", line 370, in subcmd_run
    dry_run=args.dry_run,
  File "/usr/local/lib/python3.7/dist-packages/caper/caper_runner.py", line 407, in run
    directory=work_dir, backend=backend, custom_backend_conf=custom_backend_conf
  File "/usr/local/lib/python3.7/dist-packages/caper/caper_backend_conf.py", line 362, in create_file
    hocon_s.merge(s, update=True)
  File "/usr/local/lib/python3.7/dist-packages/caper/hocon_string.py", line 165, in merge
    d = HOCONString(b).to_dict()
  File "/usr/local/lib/python3.7/dist-packages/caper/hocon_string.py", line 146, in to_dict
    c = ConfigFactory.parse_string(hocon_str)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_parser.py", line 181, in parse_string
    return ConfigParser().parse(content, basedir, resolve, unresolved_value)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_parser.py", line 494, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 4065, in parseImpl
    raise ParseSyntaxException._from_exception(pe)
pyparsing.ParseSyntaxException: Expected "}", found '"'  (at char 253), (line:4, col:149)

```

**Comment by HenryCWong** [comment]
Never mind I'm stupid, I forgot 2 double quotes at the beginning there. Sorry about that.
