### ISSUE TITLE
Example WDL file

### ISSUE THREAD

**Issue by lwtan90** [ENCODE-DCC/caper#131]
Hi,

I am working with Stanford SCG cluster.
I am wondering if you are kind enough to share an example of working WDL file (for RNA-seq pipeline using caper) for me to adapt? Also, if you don't mind, a json file. I can't seem to find in your github (especially WDL).
Thanks.

Wil

**Comment by leepc12** [comment]
Please use our atat-seq-pipeline for testing. It includes WDL and example JSON based on URLs so Caper will automatically download them.
```
$ git clone https://github.com/ENCODE-DCC/atac-seq-pipeline
$ cd atac-seq-pipeline
$ caper run (or submit) atac.wdl -i example_input_json/ENCSR356KRQ_subsampled.json
```
