### ISSUE TITLE
Caper (wgbs-pipeline) not finding make_metadata_csv.py and make_conf.py

### ISSUE THREAD

**Issue by ebprideaux** [ENCODE-DCC/caper#145]
Hi,

I am trying to analyze WGBS data using the Encode wgbs-pipeline via Caper on a Slurm cluster with CentOS Linux.  The job is repeatedly exiting with an error that seems to be related to not finding make_metadata_csv.py and make_conf.py (slurm out and cromwell out files attached).  Could you help with this?  I appreciate it!

Please see confirmation of necessary versions and other info below:

Job submission
`sbatch -p compute0 -J Caper_WGBS --export=ALL --mem 5G -t 4-0 --wrap "caper run $wdl -i $json_input"`

Java version >=1.8
```
-bash-4.2$ java -version
java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
```

Python version >= 3.6
```
-bash-4.2$ python --version
Python 3.7.3
```

When I run caper test command, no immediately apparent issues (caper version 1.6.3)
```
-bash-4.2$ caper
usage: caper [-h] [-v]
             {init,run,server,submit,abort,unhold,list,metadata,troubleshoot,debug,gcp_monitor,gcp_res_analysis,cleanup}
...

-bash-4.2$ caper -v
1.6.3
```

Have validated wdl and json input (json file attached)
```
-bash-4.2$ java -jar womtool-69.jar validate -i $json_input $wdl 
Success!
```
[RHwgbsinput.json.txt](https://github.com/ENCODE-DCC/caper/files/7341584/RHwgbsinput.json.txt)

Default.conf details
```
-bash-4.2$ cat ~/.caper/default.conf 

backend=slurm

# define one of the followings (or both) according to your
# cluster's SLURM configuration.
slurm-partition=compute0
slurm-account=

# Hashing strategy for call-caching (3 choices)
# This parameter is for local (local/slurm/sge/pbs) backend only.
# This is important for call-caching,
# which means re-using outputs from previous/failed workflows.
# Cache will miss if different strategy is used.
# "file" method has been default for all old versions of Caper<1.0.
# "path+modtime" is a new default for Caper>=1.0,
#   file: use md5sum hash (slow).
#   path: use path.
#   path+modtime: use path and modification time.
local-hash-strat=path+modtime

# Local directory for localized files and Cromwell's intermediate files
# If not defined, Caper will make .caper_tmp/ on local-out-dir or CWD.
# /tmp is not recommended here since Caper store all localized data files
# on this directory (e.g. input FASTQs defined as URLs in input JSON).
local-loc-dir=

cromwell=/home/barton/.caper/cromwell_jar/cromwell-59.jar
womtool=/home/barton/.caper/womtool_jar/womtool-59.jar
```

cromwell.out detail
[cromwell.out.txt](https://github.com/ENCODE-DCC/caper/files/7341567/cromwell.out.txt)

slurm.out detail
[slurm-34577727.out.txt](https://github.com/ENCODE-DCC/caper/files/7341571/slurm-34577727.out.txt)

**Comment by leepc12** [comment]
I found this in your log. `which` failed. Caper failed to find wrapper python scripts of the pipeline.
```
which: no make_metadata_csv.py in (/home/barton/bin/jdk-11.0.12/bin:/home/barton/bin/anaconda3/bin:/opt/ohpc/pub/compiler/gcc/5.4.0/bin/:/opt/ohpc/pub/compiler/nvidia/bin/:/bin:/home/barton/bin/anaconda3/bin:/opt/ohpc/pub/compiler/gcc/5.4.0/bin/:/opt/ohpc/pub/compiler/nvidia/bin/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/barton/bin:/opt/wangcluster/git/2.12.1:/opt/wangcluster/Taiji/1.2.0/bin:/home/barton/bin/bwa-0.7.17:/home/barton/bin/samtools-1.9:/home/barton/.local/bin:/home/barton/bin/sratoolkit.2.9.6-1-centos_linux64/bin:/home/barton/.aspera/cli/bin:/home/barton/bin/dos2unix-7.4.0:/home/barton/bin/bedtools2-master/bin:/home/barton/bin/STAR-master/bin/Linux_x86_64_static:/home/barton/bin/RSEM-1.3.1:/home/barton/bin/FastQC:/home/barton/bin/samblaster-master:/home/barton/bin/skewer-master:/home/barton/bin/UCSCtools:/home/barton/bin/pepatac-master:/home/barton/bin/subread-2.0.0-source/bin:/home/barton/bin/bcftools-1.12/bin:/home/barton/bin/htslib-1.12/bin:/home/barton/bin/gen3-client:/home/barton/bin/gatk-4.2.0.0:/home/barton/bin/cufflinks-2.2.1.Linux_x86_64:/home/barton/bin/score-client-5.8.0/bin:/home/barton/bin:/opt/wangcluster/git/2.12.1:/opt/wangcluster/Taiji/1.2.0/bin:/home/barton/bin/bwa-0.7.17:/home/barton/bin/samtools-1.9:/home/barton/.local/bin:/home/barton/bin/sratoolkit.2.9.6-1-centos_linux64/bin:/home/barton/.aspera/cli/bin:/home/barton/bin/dos2unix-7.4.0:/home/barton/bin/bedtools2-master/bin:/home/barton/bin/STAR-master/bin/Linux_x86_64_static:/home/barton/bin/RSEM-1.3.1:/home/barton/bin/FastQC:/home/barton/bin/samblaster-master:/home/barton/bin/skewer-master:/home/barton/bin/UCSCtools:/home/barton/bin/pepatac-master:/home/barton/bin/subread-2.0.0-source/bin:/home/barton/bin/bcftools-1.12/bin:/home/barton/bin/htslib-1.12/bin:/home/barton/bin/gen3-client:/home/barton/bin/gatk-4.2.0.0:/home/barton/bin/cufflinks-2.2.1.Linux_x86_64:/home/barton/bin/score-client-5.8.0/bin)
```

ENCODE pipelines have a wrapper python script for each task and find it with `which`.
So those task wrappers should exist somewhere on your `PATH` (env var).

https://github.com/ENCODE-DCC/wgbs-pipeline/blob/dev/wgbs-pipeline.wdl#L221

Make a new directory and copy these python files to it and add that directory to `PATH` in your `~/.bashrc`.
https://github.com/ENCODE-DCC/wgbs-pipeline/tree/dev/wgbs_pipeline

**Comment by ebprideaux** [comment]
I made those changes to path and made executable with chmod a+x.  Confirmed that those scripts can now be accessed.
```
-bash-4.2$ which make_metadata_csv.py
~/bin/wgbs-pipeline-dev/wgbs_pipeline/make_metadata_csv.py
```
Now there are new errors... it looks like it is failing to find a gembs command:

> ==== NAME=wgbs.index_reference, STATUS=Failed, PARENT=
> SHARD_IDX=-1, RC=1, JOB_ID=6653
> START=2021-10-14T22:27:50.346Z, END=2021-10-14T22:28:26.078Z
> STDOUT=/resource3/data/WGBS/Processed_Caper/wgbs/3ae4f213-a18f-4c86-a28a-f6e7f7d0a9da/call-index_reference/attempt-2/execution/stdout
> STDERR=/resource3/data/WGBS/Processed_Caper/wgbs/3ae4f213-a18f-4c86-a28a-f6e7f7d0a9da/call-index_reference/attempt-2/execution/stderr
> STDERR_CONTENTS=
> /resource3/data/WGBS/Processed_Caper/wgbs/3ae4f213-a18f-4c86-a28a-f6e7f7d0a9da/call-index_reference/attempt-2/execution/script: line 33: gemBS: command not found
> ln: failed to access '/resource3/data/WGBS/Processed_Caper/wgbs/3ae4f213-a18f-4c86-a28a-f6e7f7d0a9da/call-index_reference/attempt-2/execution/indexes/*.contig.sizes': No such file or directory

Is this another area where I need to add a section to path?  Or add gemBS?

**Comment by leepc12** [comment]
That look like hardcoded here.
https://github.com/ENCODE-DCC/wgbs-pipeline/blob/dev/wgbs-pipeline.wdl#L21

Please download them and edit your local WDL to point them.

**Comment by ebprideaux** [comment]
It looks like the pipeline is running now.  I appreciate the help!

To summarize, if you need to run the wgbs-pipeline without docker or singularity (and you use conda to manage packages), you will need to complete a few extra steps to configure:
1.  Add the ~/bin/wgbs-pipeline-dev/wgbs_pipeline/ to PATH variable and make contents executable
2.  Install gemBS with conda
3. Edit  '/software/conf/IHEC_standard.conf' and '/software/conf/IHEC_RRBS.conf' on line 21 of wgbs-pipeline.wdl to their actual location in your installation
