### ISSUE TITLE
pyyaml error when create_instance.sh

### ISSUE THREAD

**Issue by TarjinderSingh** [ENCODE-DCC/caper#168]
First, thank you for writing this awesome tool!

When using `create_instance.sh` to spin up a GCP virtual machine, the startup script breaks due to a pip installation error (see below). This is some sort of error with distutil: https://stackoverflow.com/questions/53807511/pip-cannot-uninstall-package-it-is-a-distutils-installed-project and https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml.

Any simple fix to address this? Thanks!

```
Apr 21 00:52:16 cromwell-01 GCEMetadataScripts[2572]: 2022/04/21 00:52:16 GCEMetadataScripts: startup-script:   Attempting uninstall: pyyaml
Apr 21 00:52:16 cromwell-01 GCEMetadataScripts[2572]: 2022/04/21 00:52:16 GCEMetadataScripts: startup-script:     Found existing installation: PyYAML 5.3.1
Apr 21 00:52:16 cromwell-01 GCEMetadataScripts[2572]: 2022/04/21 00:52:16 GCEMetadataScripts: startup-script: ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it >
Apr 21 00:52:17 cromwell-01 sudo[13856]: pam_unix(sudo:session): session closed for user root
Apr 21 00:52:17 cromwell-01 GCEMetadataScripts[2572]: 2022/04/21 00:52:17 GCEMetadataScripts: startup-script exit status 1
Apr 21 00:52:17 cromwell-01 GCEMetadataScripts[2572]: 2022/04/21 00:52:17 GCEMetadataScripts: Finished running startup scripts.
```

**Comment by TarjinderSingh** [comment]
There is a straightforward fix.  In `create_instance.sh`, add the `--ignore-installed` flag to `pip install`. 

`sudo pip install --ignore-installed caper croo`

Fixes the `pyyaml` and other installation errors.

**Comment by TarjinderSingh** [comment]
It seems like the `--ignore-installed` has been removed in the recent version. I have to add in back manually in `create_instance.sh` to get it work properly.

**Comment by leepc12** [comment]
Thanks for report. This will be fixed in the next release.
