### ISSUE TITLE
Changing `gcp-out-dir` when using `caper submit`

### ISSUE THREAD

**Issue by TarjinderSingh** [ENCODE-DCC/caper#169]
I used `create-instance.sh` to start a Cromwell server and set a default `gcp-out-dir`. I want to submit jobs with different `gcp-out-dir`. I can do this using `caper run` which takes a `--gcp-out-dir` flag. This flag does not exist for `caper submit`. Is there a way to change the out-dir when using submit command?

**Comment by leepc12** [comment]
`caper submit` is a client-side command. You cannot change the output directory on a client side.
You need to restart `caper server --gcp-out-dir` (or gcp-out-dir defined in `~/.caper/default.conf`).
