### ISSUE TITLE
Error when submitting to caper server on SGE

### ISSUE THREAD

**Issue by asanghi7** [ENCODE-DCC/caper#17]
When I submit my atac-seq input.json files to the caper server. I get the following error:
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b9025e3c7b8>: Failed to establish a new connection: [Errno 111] Connection refused'))...I attached my default.conf file. 
[default.conf.txt](https://github.com/ENCODE-DCC/caper/files/3383225/default.conf.txt)

**Comment by leepc12** [comment]
That HTTP error tells you that Caper server IP address (specified by --ip) is not configured correctly. It's `localhost` by default. Get a hostname of Caper server and put it into your conf file.

If you `qsub`ed Caper server like `echo "caper server" | qsub`, then your caper server should be running on a compute node you need to take a hostname of that node.
```
ip=YOUR_CAPER_SERVER_HOSTNAME
```

If you ran Caper server on a login node then you don't need to specify `--ip`.

Also, I don't think your parallel environment is configured correctly. `dper730xd-srcf-d16-17` looks like a hostname of Caper server?
```
sge-pe=dper730xd-srcf-d16-17
```

**Comment by asanghi7** [comment]
Thank you for the response. I understand that I shouldn't be using sge-pe. I will set the ip to the Hostname from my slurm job

**Comment by leepc12** [comment]
Yes `sge-pe` is for SGE, not for SLURM. We already met in person and fixed this.
