### ISSUE TITLE
Unable to write file due to disk space despite there being sufficient disk space via docker

### ISSUE THREAD

**Issue by alesgarces22** [ENCODE-DCC/caper#173]
I'm trying to run a pipeline via caper with a docker environment. Initially I thought the error was really a permissions error, however even after adjusting all the permissions to all docker and pipeline related directories and files, this error still appears:

"docker: write /var/lib/docker/tmp/GetImageBlob197301894: no space left on device."

However when I check my disk space and docker container space, there appears to be ample space left. What other source could be responsible for contributing disk space?

**Comment by leepc12** [comment]
Please check your disk space on that directory `/var/lib/docker/tmp`.
```
$ sudo df -h /var/lib/docker/tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       156G   21G  128G  14% /
```

**Comment by alesgarces22** [comment]
@leepc12 Thank you so much! As it turns out my filesystem was full, I just didn't realize docker was accessing space from that drive.

**Comment by leepc12** [comment]
I see. I am closing this ticket. Please reopen if you have further issues.
