### ISSUE TITLE
Newer cromwell versions

### ISSUE THREAD

**Issue by TarjinderSingh** [ENCODE-DCC/caper#176]
Hello, 
When using `caper init`, it installs Cromwell version 65, which doesn't support version 1.1 of Cromwell. Is there a reason why caper installs the earlier builds of Cromwell? If we change the jar to the more updated Cromwell, does everything still work mostly fine?

**Comment by leepc12** [comment]
I haven't tested Caper with latest Cromwell versions yet. I will do it sometime this week but I think it should work with recent Cromwell versions.

You can replace old Cromwell/Womtool (`cromwell=` and `womtool=`) with github-release URLs of new Cromwell/Womtool in Caper's conf `~/.caper/default.conf` and see if it works.

**Comment by leepc12** [comment]
Upgraded Cromwell to 82 in v2.2.2.
I am closing this issue. Feel free to reopen if you get any problem with new Cromwell.
