### ISSUE TITLE
Do I use the caper or scg version of reference?

### ISSUE THREAD

**Issue by asanghi7** [ENCODE-DCC/caper#18]
I'm wondering if I should point my reference to the caper links or the scg links in my input.json file for the atac-seq pipeline

**Comment by leepc12** [comment]
Cromwell's input JSON file does not allow URLs. Other than that, you can use your input.json without Caper.

**Comment by asanghi7** [comment]
Great, I will still use the scg version of the reference tsk since it points to directories in scg.

**Comment by leepc12** [comment]
You should use `_scg.tv` on SCG. We met in person and fixed it.
