### ISSUE TITLE
Error related to caper server on scg node

### ISSUE THREAD

**Issue by asanghi7** [ENCODE-DCC/caper#19]
I received this error after I submitted jobs to my caper server. I think the scg node isn't compatible. Error below

HTTPConnectionPool(host='sgisummit-frcf-111-28', port=8000): Max retries exceeded with url: /api/workflows/v1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2aba5d2e2fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by leepc12** [comment]
This means that your caper server is dead or not running on `sgisummit-frcf-111-28`.

**Comment by leepc12** [comment]
We met in person and fixed it.
