### ISSUE TITLE
I 'pip install caper', but cannot run '$caper'

### ISSUE THREAD

**Issue by tanpuekai** [ENCODE-DCC/caper#21]
Hi, 

I follow your readme, and run this line on our server:
`python3 -m pip install caper --user`

Then I checked that caper can indeed be loaded:
```
$ python3
Python 3.6.4 (default, May 28 2019, 12:12:54)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import caper
>>>
```
but i cannot run caper under the $ sign:
```
$ caper
bash: caper: command not found...
```
In your README landing page, you clearly say that installation is either by `pip` **or** by `git clone`, why can't I run `$caper` after I chose the first way which is by `pip`?

[The `git clone` method works for me though, but using it to run your atac-pipeline produced tons of errors, pointing to dependencies not installed or loaded. See [https://github.com/ENCODE-DCC/atac-seq-pipeline/issues/149](url). Thus i tried to see if `pip `installation of `caper `will resolve the issue]

We chose your software because we liked the big name '**ENCODE**' on it. But your software is certainly not easy to use. Very painful sometimes. Can you pls kindly help. Thanks!

**Comment by leepc12** [comment]
Instruction for `~/.local/bin` issue will be added to next version. Closing this.
