### ISSUE TITLE
caper init subcommand DNE

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/caper#23]
Hello, for clarity, can you please remove Step 5 `caper init [PLATFORM]` from the README since it looks the config file is now generated by running `caper` without any arguments?

**Comment by leepc12** [comment]
No, `caper` without any arguments (step 3) creates an empty conf file. Step 5 is necessary to make a non-empty conf file for a specific platform.

**Comment by nicolerg** [comment]
Is there a way to see which version of the software this repo is on? I am using the version of caper installed on SCG, which may be outdated (0.3.20). I get `caper: error: argument action: invalid choice: 'init' (choose from 'run', 'server', 'submit', 'abort', 'unhold', 'list', 'metadata', 'troubleshoot', 'debug')` when I try to run Step 5.

**Comment by nicolerg** [comment]
The "Configuration file" section of `DETAILS.md` also says `Run Caper without parameters to generate a default configuration file. Caper automatically creates a default configuration file at ~/.caper/default.conf. Such configruation file comes with all available parameters commented out. You can uncomment/define any parameter to activate it.` Perhaps I am using an older version that corresponds with this doc because that is what I see.

**Comment by leepc12** [comment]
Thanks for reporting this. Removed that confusing part from `DETAILS.md`.

**Comment by nicolerg** [comment]
Thanks. Can you also clarify in the ENCODE ATAC-seq pipeline documentation that you do not need to install `caper` if you are using `conda` since setting up the conda environment already installs `caper`? I got mixed up between the older version of `caper` installed on SCG and the (newer) version that is pointed to after activating the conda environment.

**Comment by leepc12** [comment]
Sure, will do.

**Comment by nicolerg** [comment]
Related to above, can you also clarify that you do not need to install `croo` if you are using the Conda environment?
