### ISSUE TITLE
slurmstepd: error: *** JOB CANCELLED DUE TO TIME LIMIT ***

### ISSUE THREAD

**Issue by tAndreani** [ENCODE-DCC/caper#36]
Hello,  

I am trying to run a WDL workflow using caper and the scheduler SLURM. I have noticed that my "children" jobs (named cromwell) stop after around 15 minutes preventing the entire workflow to finish all the process. The main job is still running until a point in which it stops showing that the workflow failed. Why is this happening? Is this due to the time value in the backend.conf file? (time=24 in the content of the backend.conf see below).

```
 slurm {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
	default-runtime-attributes {
          time = 24
          slurm_partition = "long"
          slurm_account = "jgu-cbdm"
        }
	script-epilogue = "sleep 10 && sync"
        concurrent-job-limit = 1000
        runtime-attributes = """
	String? docker
        String? docker_user
        Int cpu = 1
        Int? gpu
        Int? time
        Int? memory_mb
        String? slurm_partition
        String? slurm_account
        String? slurm_extra_param
        String? singularity
        String? singularity_bindpath
        String? singularity_cachedir
```

I tried to provide a different amount of time while running the workflow such as adding the option -t with 120 hours as follow:  

```  
sbatch -p long -A jgu-cbdm -J test_caper_scMeth -t 120:00:00 --export=ALL --mem 16G --wrap "caper run scMeth.wdl -i scMeth.json"

```
but this did not help. How could I modify the time=24? Is 24 minutes or hours? If this is not the problem how can I solve this issue? Though my jobs are killed after running for 15 minutes..

I have investigated what might be the problem consulting this post:  

https://stackoverflow.com/questions/34653226/job-unexpectedly-cancelled-due-to-time-limit  

Basically what I am noticing is that the jobs killed after 15 minutes are only the ones named "Cromwell". The main job is not killed. Is it possible that the "Cromwell" jobs run with other time parameters? Looking at the partitions of my cluster, for the "long" partition by default there are only 15 minutes available in the DefaultTime parameter. Check here when I type:

`scontrol show partitions long`  
  
I have this:  

```
PartitionName=long
   AllowGroups=ALL DenyAccounts=none AllowQos=ALL
   AllocNodes=ALL Default=NO QoS=long_limits
   DefaultTime=00:15:00 DisableRootJobs=NO ExclusiveUser=NO GraceTime=0 Hidden=NO
   MaxNodes=1 MaxTime=5-00:00:00 MinNodes=1 LLN=NO MaxCPUsPerNode=63
   Nodes=a[0004-0018,0022-0263,0265-0287,0289-0338,0340-0360,0362-0533,0535-0550,0552-0555]
   PriorityJobFactor=1 PriorityTier=1 RootOnly=NO ReqResv=NO OverSubscribe=NO
   OverTimeLimit=NONE PreemptMode=OFF
   State=UP TotalCPUs=34752 TotalNodes=543 SelectTypeParameters=NONE
   DefMemPerCPU=300 MaxMemPerNode=UNLIMITED
   TRESBillingWeights=cpu=1.0,mem=0.25G
```
It should be this the problem. Jobs are run with the default parameters above. Any idea how to prevent this?

Thanks in advance for any reply
Tommaso

**Comment by leepc12** [comment]
That is 24 hours and has nothing to do with you 15 minute failures. Can you define runtime attributes like the following for every task in your WDL and try again?

```
	runtime {
		cpu : 1
		memory : '${mem_mb} MB'
		time : time_hr
	}
```

**Comment by tAndreani** [comment]
It seems to work. Can I ask you why LSF is not available for CAPER? I would like to run my WDL also on a LSF scheduler. Thanks in advance

**Comment by leepc12** [comment]
I don't have an LSF environment to test Caper with. If you can provide a `SUBMIT` part (for example of SLURM: https://github.com/ENCODE-DCC/caper/blob/master/caper/caper_backend.py#L376) of the `backend.conf` for a general LSF cluster then I can simply add it to Caper.

**Comment by tAndreani** [comment]
Do you need the info from  https://github.com/ENCODE-DCC/caper/blob/master/caper/caper_backend.py#L376 to https://github.com/ENCODE-DCC/caper/blob/master/caper/caper_backend.py#L400  ? I think I have it, let me check it tomorrow, now its late here in Europe. First think i'll do tomorrow. Is your email this leepc12@gmail.com? I will send you that part of the SUBMIT  file there.

**Comment by leepc12** [comment]
I got your email. Thanks for your contribution.
We are currently working on refactoring Caper code and will add LSF backend to Caper soon after that.

**Comment by tAndreani** [comment]
Hi,   
is there any update related to the adding of LSF backend in Caper?   
Thanks in advance!

**Comment by leepc12** [comment]
We are working of a complete refactoring of the code and this will take long.

**Comment by leepc12** [comment]
Please `pip uninstall caper` your current Caper. `git clone` Caper repo directly and checkout the `LSF_support` branch.
```
$ git clone https://github.com/ENCODE-DCC/caper
$ git pull origin/LSF_support
$ git checkout LSF_support
$ echo "export PATH=\"\$PATH:$PWD/caper/bin\"" >> ~/.bashrc
```

Re-login. Check if you are using the right Caper binary.
```
$ which caper
$ caper -v
```

Caper version should be `0.6.2b`.

This is your original command line for `bsub`.
```
    ssh -t mogon.research.org \
    bsub -q \
    ${if memory_mb < 6001 then "normal" else 
            ( if cpu > 3 then "big-multi" else "big")} \
    ${"-n " + cpu} \
    -R 'rusage[mem=${memory_mb}]' \
    -J ${job_name} \
    -cwd ${cwd} \
    -o ${out} \
    -e ${err} \
    /usr/bin/env bash ${script}
```

This is an actual implementation in Caper. Caper will use `-M ` (memory per CPU) instead of `-R rusage[mem=]`.
```
    bsub \
    ${-q + lsf_queue} \
    ${"-n " + cpu} \
    ${"-M " + memory_mb + "M"} \
    -J ${job_name} \
    -cwd ${cwd} \
    -o ${out} \
    -e ${err} \
    /usr/bin/env bash ${script}
```

I couldn't test it since I don't have a system with LSF installed. Please let me know if this works.

You can test it with this toy WDL. Save it to `toy.wdl`.
```
workflow test {
        call t1
}

task t1 {
        command {
                echo 1 > 1.txt
        }
        output {
                File out = '1.txt'
        }
}
```

Make a backup of your conf `~/.caper/default.conf`. Do `caper init` to make a LSF version of conf and then edit it.
```
$ caper init lsf  # this will remove all contents in your conf at ~/.caper/default.conf
```

Test with the above toy problem. This WDL doesn't require any input JSON.
```
$ caper run toy.wdl
```

**Comment by tAndreani** [comment]
Hi,  

after doing:  

`git clone https://github.com/ENCODE-DCC/caper`    

i checked inside the folder but there is not the origin/LSF_support to pull  

here is what i have inside and what it returns me the command `git pull origin/LSF_support` :

![caper](https://user-images.githubusercontent.com/6462162/70393676-bce01600-19ec-11ea-9159-fef75683eedd.png)

Am I missing something? Thanks for your cooperation.

**Comment by tAndreani** [comment]
Maybe this can further help:  

![help2](https://user-images.githubusercontent.com/6462162/70393965-77254c80-19f0-11ea-95d9-b4b879398bb8.png)

**Comment by leepc12** [comment]
I hope this helps:
```
leepc12@kadru:/users/leepc12/code/temp$ git clone https://github.com/ENCODE-DCC/caper
Cloning into 'caper'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1191 (delta 7), reused 12 (delta 6), pack-reused 1170
Receiving objects: 100% (1191/1191), 362.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (801/801), done.
Checking connectivity... done.
leepc12@kadru:/users/leepc12/code/temp$ cd caper
leepc12@kadru:/users/leepc12/code/temp/caper$ git checkout origin/LSF_support
Note: checking out 'origin/LSF_support'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2a25518... new feature: LSF support
leepc12@kadru:/users/leepc12/code/temp/caper$ ll
total 76
drwxr-xr-x 6 leepc12 users  4096 Dec  8 20:04 ./
drwxr-xr-x 7 leepc12 users  4096 Dec  8 20:04 ../
drwxr-xr-x 2 leepc12 users  4096 Dec  8 20:04 bin/
drwxr-xr-x 3 leepc12 users  4096 Dec  8 20:04 caper/
-rw-r--r-- 1 leepc12 users 24181 Dec  8 20:04 DETAILS.md
drwxr-xr-x 2 leepc12 users  4096 Dec  8 20:04 docs/
drwxr-xr-x 8 leepc12 users  4096 Dec  8 20:04 .git/
-rw-r--r-- 1 leepc12 users  1267 Dec  8 20:04 .gitignore
-rw-r--r-- 1 leepc12 users  1067 Dec  8 20:04 LICENSE
-rw-r--r-- 1 leepc12 users 14699 Dec  8 20:04 README.md
-rw-r--r-- 1 leepc12 users   899 Dec  8 20:04 setup.py
leepc12@kadru:/users/leepc12/code/temp/caper$ cat caper/caper_args.py | grep LSF
from .caper_backend import BACKEND_LSF
DEFAULT_CONF_CONTENTS_LSF = """backend=lsf
    elif backend == BACKEND_LSF:
        contents = DEFAULT_CONF_CONTENTS_LSF
    group_lsf = parent_submit.add_argument_group('LSF arguments')
        '--lsf-queue', help='LSF queue.')
        help='LSF extra parameters. Must be double-quoted')
```

Once you successfully cloned that branch then add the directory `caper/bin` to your `PATH` in your `~/.bashrc`.

**Comment by tAndreani** [comment]
Hi,  

it seems fine the first steps. Then when I do:  

` echo "export PATH=\"\$PATH:$PWD/caper/bin\"" >> ~/.bashrc`

the path is correctly added infact:  

`nano ~/.bashrc`  

returns me:  

```
export export PATH="$PATH:/data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/caper/caper/bin"

```

now if I try caper it seems that I do no have installed `pyhocon`. Let me try to ask the administrator of my cluster if they can install it. I have also searched if this problem happened already for caper and found this:  

https://www.gitmemory.com/issue/ENCODE-DCC/caper/14/507379516  

so someone else encountered the same problem..

Thanks

**Comment by leepc12** [comment]
Install it with `pip install pyhocon`.
Check caper version before running.
```
$ caper -v
```

**Comment by tAndreani** [comment]
Ok installation worked and the version is the correct one `0.6.2b`.  

Now I run your script 

`caper run toy.wdl`  

It seems that the cluster is recognized but the job is not able to be dispatched. Here the error from  task1 in the stdout file (within the execution folder):  

```
Sender: LSF System <lsfadmin@cmu118>
Subject: Job 408824: <cromwell_8e991367_t1> Exited

Job <cromwell_8e991367_t1> was submitted from host <eris1n2> by user <ta779> in cluster <cmucluster>.
Job was executed on host(s) <cmu118>, in queue <defaultlow>, as user <ta779> in cluster <cmucluster>.
</PHShome/ta779> was used as the home directory.
</data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/8e991367-a18b-4c89-889a-414848245fc6/call-t1> was used as the working directory.
Started at Mon Dec  9 12:11:06 2019
Results reported at Mon Dec  9 12:11:06 2019

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
all
------------------------------------------------------------

Exited with exit code 127.

Resource usage summary:

    CPU time   :      0.02 sec.
    Max Memory :         4 MB
    Max Swap   :        34 MB

    Max Processes  :         1
    Max Threads    :         1

The output (if any) follows:



PS:

Read file <nv> for stderr output of this job.
```
in the nv file (output of the task1) i have:  

```
/PHShome/ta779/.lsbatch/1575911451.408824: line 8: all: command not found
```

from task2 instead, I have this error in the stderr.submit file within the execution folder:  

`1M: MEMLIMT value should be a positive integer. Job not submitted.`  

any idea? Let me know if you need more info.

**Comment by leepc12** [comment]
I think your `--lsf_extra_param` is malformed. How did you define it (either in command line or in conf file)?

Please post your conf file.
Also can I get more log files from the cluster engine like `/PHShome/ta779/.lsbatch/1575911451.408824`? Any log/script file related to the job 408824 will be helpful.

**Comment by tAndreani** [comment]
I did not define the `--lsf_extra_param` where should I define it? And also for which parameter/option?  

this is the configuation file:  

```
backend=lsf

lsf-partition=long

tmp-dir=/tmp/
```
this is how i run caper:  

`bsub -q long -M 80 --wrap "caper run toy.wdl"`   

this is the workflow.log:  
```
2019-12-10 06:23:40,898 INFO  - MaterializeWorkflowDescriptorActor [UUID(2d9f1493)]: Parsing workflow as WDL draft-2
2019-12-10 06:23:41,484 INFO  - MaterializeWorkflowDescriptorActor [UUID(2d9f1493)]: Call-to-Backend assignments: test.t1 -> lsf, test.t2 -> lsf
2019-12-10 06:23:42,795 INFO  - WorkflowExecutionActor-2d9f1493-f43d-4d91-b9eb-efc478120f00 [UUID(2d9f1493)]: Starting test.t1, test.t2
2019-12-10 06:23:44,678 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t1:NA:1]: `echo 1 > 1.txt`
2019-12-10 06:23:44,738 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t1:NA:1]: executing: echo "/bin/bash /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t1/execution/script #         if [ -z \"$SINGULARITY_BINDPATH\" ]; then         export SINGULARITY_BINDPATH=; fi;         if [ -z \"$SINGULARITY_CACHEDIR\" ]; then         export SINGULARITY_CACHEDIR=; fi;         singularity exec --cleanenv --home /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t1                   /bin/bash /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t1/execution/script" | bsub         -J cromwell_2d9f1493_t1         -cwd /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t1         -o /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t1/execution/stdout         -e /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t1/execution/stderr                                                               -env all
2019-12-10 06:23:45,405 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t1:NA:1]: job id: 427446
2019-12-10 06:23:45,410 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t1:NA:1]: Cromwell will watch for an rc file *and* double-check every 180 seconds to make sure this job is still alive
2019-12-10 06:23:45,412 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t1:NA:1]: Status change from - to Running
2019-12-10 06:23:46,481 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t2:NA:1]: `echo 2 > 2.txt`
2019-12-10 06:23:46,498 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t2:NA:1]: executing: echo "/bin/bash /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t2/execution/script #         if [ -z \"$SINGULARITY_BINDPATH\" ]; then         export SINGULARITY_BINDPATH=; fi;         if [ -z \"$SINGULARITY_CACHEDIR\" ]; then         export SINGULARITY_CACHEDIR=; fi;         singularity exec --cleanenv --home /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t2                   /bin/bash /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t2/execution/script" | bsub         -J cromwell_2d9f1493_t2         -cwd /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t2         -o /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t2/execution/stdout         -e /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/test_caper/test/2d9f1493-f43d-4d91-b9eb-efc478120f00/call-t2/execution/stderr         -n 3         -M $(expr 5 / 3)M         -W 10:00                                    -env all
2019-12-10 06:27:03,730 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t1:NA:1]: executing: bjobs -l 427446
2019-12-10 06:30:14,792 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(2d9f1493)test.t1:NA:1]: executing: bjobs -l 427446

```
actually in this folder `/PHShome/ta779/.lsbatch/` I don't have anything like now I have the same problem with this message `/PHShome/ta779/.lsbatch/1575977850.427450: line 8: all: command not found`  but if I look inside  `/PHShome/ta779/.lsbatch/` it is empty.  I don't know how to interpret this..

**Comment by leepc12** [comment]
Please read Caper's README carefully. You should not use `/tmp`  ad `tmp-dir` in your conf. Caper stores all important temp files and cached big files there.
```
tmp-dir=/tmp
```

`line 8: all: command not found` means that the `bsub` submit command is wrong.I need to look at `backend.conf` in `tmp-dir` but you specified it as `/tmp` so it will be no longer there.
```
cd /tmp
find -name `backend.conf`
```

Can I get access to your cluster somehow? Can you talk to your cluster admin to temporarily make an account for me? Is it only accessible through university's VPN or something?

**Comment by tAndreani** [comment]
let me talk to my colleagues. I'll come back to you soon.

**Comment by leepc12** [comment]
Closing this due to long inactivity.
