### ISSUE TITLE
How to specify the Cromwell version

### ISSUE THREAD

**Issue by biodavidjm** [ENCODE-DCC/caper#53]
`caper` currently downloads by default `cromwell-47.jar`. Is it possible to specify which version to download? I know that it is possible to specify which `cromwell` version to run if it is already downloaded. But what about specifying which version to download?

It would be great to know whether it's currently possible, otherwise, it would be an excellent and very useful new feature.

Thanks!

**Comment by leepc12** [comment]
Download Cromwell JAR and Womtool JAR from here.
https://github.com/broadinstitute/cromwell/releases

And specify them in your `~/.caper/default.conf` file.
```
# you can also use URL here though
cromwell=/your/local/somewhere/cromwell-48.jar
womtool=/your/local/somewhere/womtool-48.jar
```

**Comment by biodavidjm** [comment]
As I explained, I knew that option was available (sorry if it wasn't clear). Based on your answer, it seems not possible to specify from caper the version to be downloaded. But, could this be a new feature to be added to caper? It would be really helpful... 
Thanks!

**Comment by leepc12** [comment]
If you define URLs for those parameters in conf. then Caper will download them.
