### ISSUE TITLE
Fail to define tmp directory 

### ISSUE THREAD

**Issue by jessiechan0752** [ENCODE-DCC/caper#54]
Hi, Jin. Thank you for previous help of the PBS cluster issue. Now I found there's another problem regarding the temporary directory. 

I edited the "tmp-dir =" option in the file ~/.caper/default.conf, but the large files are still stored in my home directory ~/atac . 

Can you show the correct way to define a tmp directory?

Thank you!

**Comment by leepc12** [comment]
No whitespace allowed here `tmp-dir =`.

**Comment by jessiechan0752** [comment]
Hi Jin. Thank you for the suggestion. I tried what you suggested, but the problem is still there. The pipeline did create a temporary directory under my set directory, but there were only 4 files in it. On the other hand,  it also created another one in my home directory storing large files.

Here's what's in  my  `  ~/.caper/default.conf ` file:

backend=local

# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
tmp-dir="/paedwy/disk1/liangrui/caper_pipeline"

Here's what's in my defined temporary directory  ` /paedwy/disk1/liangrui/caper_pipeline/atac ` :

-rw-r--r-- 1 liangrui wlyang 7931 Mar 12 18:42 backend.conf
-rw-r--r-- 1 liangrui wlyang  115 Mar 12 18:42 labels.json
-rw-r--r-- 1 liangrui wlyang    0 Mar 12 18:43 metadata.json
-rw-r--r-- 1 liangrui wlyang   94 Mar 12 18:42 workflow_opts.json

Here's what's in home temporary directory ` /home/liangrui/atac/b485ce83-6eb8-446e-a164-39ad27301861 ` :

drwxr-xr-x 1 liangrui wlyang  80 Mar 12 18:43 call-align
drwxr-xr-x 1 liangrui wlyang 136 Mar 12 18:43 call-read_genome_tsv

Can you help for that?
Thank you !

**Comment by leepc12** [comment]
That is not `tmp-dir`. It's `out-dir`. Define `out-dir` in your conf then all outputs will be written there.
`tmp-dir` is for temporary files and cached data files.

**Comment by jessiechan0752** [comment]
Thank you so much for help Jin, the problem is solved.
