### ISSUE TITLE
initialization of  Caper (Sherlock paltform)

### ISSUE THREAD

**Issue by Kmrouj** [ENCODE-DCC/caper#59]
Hi,
I installed caper om my MacOS. I did the run test 'caper'. However, when i tried to initialize Caper using Sherlock (I work at Stanford) it did not want to. Do you think there's a step I'm missing?
Thanks 
<img width="593" alt="Screen Shot 2020-04-01 at 7 23 14 PM" src="https://user-images.githubusercontent.com/56937863/78204666-fe3e7a80-744e-11ea-8e0b-345f29f51e0c.png">

**Comment by leepc12** [comment]
Run `caper init sherlock`.

**Comment by Kmrouj** [comment]
I tried already, but it did not work
 '~ % Run caper init sherlock
zsh: command not found: Run'

Instead, I tried local, it did work. Do you think it's possible to run the pipeline on my mac (I have 4 samples/ATAC-seq data) or is better to use sherlock 
thank you

**Comment by leepc12** [comment]
Please use Bash (not zsh).
Mac will not work with a full sample due to lack of resources. It will work with subsampled test samples though.

**Comment by Kmrouj** [comment]
zsh is the default mode of MacOS. 
Yes, I'm planning to use Bash, however, I'm not able to deploy/initialize Caper on sherlock ! I can not tell where the error is ! do you know the bash command to initialize Caper either locally or on sherlock ?
Thank you

**Comment by leepc12** [comment]
`Run caper init sherlock` You should not have `Run` there. I just installed `zsh` on my computer and tested it. It worked fine. Run `caper init sherlock`.

**Comment by Kmrouj** [comment]
Yes, indeed it did work. I thought 'Run' was part of the command line.
Thank you
<img width="570" alt="Screen Shot 2020-04-02 at 8 57 51 AM" src="https://user-images.githubusercontent.com/56937863/78270848-39c55d00-74c0-11ea-80c3-fee32a8986d7.png">
