### ISSUE TITLE
respect environment variables in conf file

### ISSUE THREAD

**Issue by GodloveD** [ENCODE-DCC/caper#74]
```
$ caper --version
0.6.3
```
If I set my conf file like so, then caper uses the appropriate directory and all is right with the world.
```
$ cat ~/.caper/default.conf
backend=slurm

# define one of the followings (or both) according to your
# cluster's SLURM configuration.
slurm-partition=my_partition
slurm-account=

# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
tmp-dir="/home/some_user/caper_test"
```
But if I try to accomplish the same thing with an environment variable caper appears to get confused and try to use my `$PWD` instead?
```
$ export MY_DIR=caper_test

$ cat ~/.caper/default.conf
backend=slurm

# define one of the followings (or both) according to your
# cluster's SLURM configuration.
slurm-partition=my_partition
slurm-account=

# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
tmp-dir="/home/some_user/${MY_DIR}"
```
This is a problem.  On our system we set up temporary directories on a per-job basis that are supposed to be accessed by environment variables.  

Thanks for looking at this! 😸

**Comment by leepc12** [comment]
Any parameter in Caper can be defined either in a conf file or in a command line argument.
So when you `sbatch` your `caper run` command line as described in Caper's documentation:

$ sbatch ... --wrap 'caper run your.wdl -i input.json ... --tmp-dir ${MY_DIR}'

Make sure that you use a single quote for `sbatch`'s `--wrap` (instead of a double quote).

**Comment by GodloveD** [comment]
Follow up:  On closer examination the variable in the conf file is treated as a string literal and caper creates a directory with a dollar sign in it.  @leepc12 it's nice to know there is a workaround available at the command prompt.  Would it be useful to properly parse env vars in the conf file too?

**Comment by leepc12** [comment]
Caper's conf file cannot parse env vars. It translates every value as string literal. Did you try with the above workaround? We currently have no plan to support such env-var parsing in conf file.

**Comment by GodloveD** [comment]
The workaround works (around).  Thank you!
